[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['cd server && npm install']

[phases.build]
cmds = ['cd server && npx prisma generate && npx tsc']

[start]
cmd = 'cd server && node dist/index.js'
